web:
  restart: always
  build: ./web
  expose:
    - "8000"
  links:
    - postgres:postgres
  volumes:
    - /usr/src/app
    - /usr/src/app/static
  env_file: .env
  command: /usr/local/bin/gunicorn docker_django.wsgi:application -w 2 -b unix:/usr/src/app/docker_django.sock

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /www/static
    - /www/media
  volumes_from:
    - web
  links:
    - web:web

postgres:
  restart: always
  image: postgres:9.6
  ports:
    - "5432:5432"
  volumes:
    - pgdata:/var/lib/postgresql/data/
